#!/usr/bin/env ruby
require 'yaml'

def die(msg); puts msg; exit 1; end

def load_config!
  @config = YAML.load(File.read("#{ENV['HOME']}/.config/watch_tablet.yml"))
  unless @config['input_device']
    die "Please specify input_device in the config file"
  end
end

def config
  load_config! unless @config
  @config
end

def activate_mode(mode)
  puts "Switching to #{mode} mode"
  if cmds = config['modes'][mode]
    cmds.each{|cmd| system cmd }
  end
end

def run_watcher
  cmd = "monitor-sensor"
  io = IO.popen(cmd,"r")
  while s=io.gets
    if m=s.match(/Accelerometer orientation changed: (.+)/)
      case d=m[1]
      when "normal" then activate_mode "laptop"
      when "right-up" then activate_mode "tablet-portrait"
      when "left-up" then activate_mode "tablet-portrait"
      when "bottom-up" then activate_mode "tablet-landscape"
      end
    end
  end
rescue Interrupt
  io.close
end

run_watcher
